file_format: "1"
id: butterfree
name: Butterfree
type: shield
url: https://github.com/foostan/crkbd/
requires:
  - pro_micro
exposes:
features:
  - keys
siblings:
  - butterfree_left
  - butterfree_right